#!/usr/bin/env python3
"""amalgamate_kainc.py — Topological amalgamation for kainc self-host compiler.
TurboKain doctrine: modular source -> single whole-program .kn -> LLVM WPO.

Usage:
    python scripts/amalgamate_kainc.py [-o kainc.kn]

- Orders files in true dependency order (not alphabetical).
- Strips internal relative `use` (keeps only `use std::`).
- Strips legacy module prefixes (types., ast., orchestrator., jit_*) as safety net.
- Dedupes top-level symbols: keeps FIRST definition, comments out later
  redefinitions (SELF-CONTAINED mirrors for standalone check).
- Excludes *test.kn integration tests from the binary (use `kain test` for those).
"""
import re
import sys
import pathlib

REPO = pathlib.Path(__file__).resolve().parent.parent
SRC = REPO / "src"

# Flat layout (src/core/): numeric prefixes encode pipeline stage, so
# alphabetical order IS dependency order. Mirrors/duplicates were deleted
# from src (see git log); the deduper below is a backstop, not the plan.
# NOTE: build.kn + llvm_stub_types.kn retired to attic/;
# L5/L6_test.kn live in tests/ (kain test), not in the binary.
ORDER = [
    "src/core/00_token.kn",
    "src/core/00_error.kn",
    "src/core/00_span.kn",
    "src/core/00_ast.kn",
    "src/core/00_builtins.kn",
    "src/core/42_runtime.kn",
    "src/core/00_effects.kn",
    "src/core/30_types.kn",
    "src/core/10_lexer.kn",
    "src/core/20_parser.kn",
    "src/core/31_monomorphize.kn",
    "src/core/41_llvm_ffi.kn",
    "src/core/72_jit_metal.kn",
    "src/core/74_jit_x86.kn",
    "src/core/73_jit_orc.kn",
    "src/core/71_jit_cache.kn",
    "src/core/70_jit.kn",
    "src/core/60_L1_state.kn",
    "src/core/61_L2_integrity.kn",
    "src/core/62_L3_dispatch.kn",
    "src/core/63_L4_stage.kn",
    "src/core/64_L5_temporal.kn",
    "src/core/65_L6_stones.kn",
    "src/core/66_L7_systems.kn",
    "src/core/90_GpuBackend.kn",
    "src/core/40_codegen.kn",
    "src/core/52_compiler.kn",
    "src/core/53_orchestrator.kn",
    "src/core/54_shared.kn",
    "src/core/55_registry.kn",
    "src/core/56_builtin_handlers.kn",
    "src/core/87_theme.kn",
    "src/core/83_metadata.kn",
    "src/core/80_command.kn",
    "src/core/84_session.kn",
    "src/core/85_source.kn",
    "src/core/82_highlight.kn",
    "src/core/81_evaluation.kn",
    "src/core/86_terminal.kn",
    "src/core/51_cli.kn",
    "src/core/50_main.kn",
]

# Matches top-level symbol definitions we dedupe.
# Kain top-level forms: pub struct X, pub enum X, pub const X, pub fn X,
#   pub type X, struct X, enum X, const X, fn X, type X
DEF_RE = re.compile(
    r"^\s*(pub\s+)?(struct|enum|const|fn|type)\s+([A-Za-z_][A-Za-z0-9_]*)"
)

USE_RE = re.compile(r"^\s*use\s+(\S+)")

PREFIX_RES = [
    (re.compile(r"\btypes\.(?!kn\b)"), ""),
    (re.compile(r"\bast\.(?!kn\b)"), ""),
    (re.compile(r"\borchestrator\.(?!kn\b)"), ""),
    (re.compile(r"\bjit_metal\.(?!kn\b)"), ""),
    (re.compile(r"\bjit_x86\.(?!kn\b)"), ""),
    (re.compile(r"\bjit_cache\.(?!kn\b)"), ""),
    (re.compile(r"\bjit_orc\.(?!kn\b)"), ""),
]


def strip_internal_uses(line: str) -> str | None:
    """Return None if line is an internal use to drop, else possibly rewritten line."""
    m = USE_RE.match(line)
    if not m:
        return line
    target = m.group(1)
    if target.startswith("std::"):
        return line
    return None  # drop internal relative use


def main() -> int:
    out_path = pathlib.Path(sys.argv[2] if len(sys.argv) > 2 and sys.argv[1] == "-o" else REPO / "kainc.kn")
    if len(sys.argv) > 2 and sys.argv[1] == "-o":
        out_path = pathlib.Path(sys.argv[2])
    if not out_path.is_absolute():
        out_path = pathlib.Path.cwd() / out_path

    seen: dict[str, str] = {}  # symbol -> first file
    skipped: list[str] = []
    out_lines: list[str] = []
    out_lines.append("// kainc.kn — Topological Amalgamation of kainc self-host compiler\n")
    out_lines.append("// Generated by scripts/amalgamate_kainc.py — DO NOT EDIT. Edit src/ instead.\n")
    out_lines.append("// Order: Token->Error->Span->AST->Types->Lexer->Parser->Codegen->CLI->REPL->Main\n\n")

    for rel in ORDER:
        full = REPO / rel
        if not full.exists():
            print(f"WARN: missing {rel}, skipping")
            continue
        out_lines.append(f"\n// === BEGIN: {rel} ===\n")
        text = full.read_text(encoding="utf-8")
        # Safety net: strip legacy module prefixes (src should already be clean).
        for rx, rep in PREFIX_RES:
            text = rx.sub(rep, text)
        lines = text.splitlines(keepends=True)
        i = 0
        in_block_skip = False
        brace_depth = 0
        while i < len(lines):
            line = lines[i]
            # Drop internal uses
            stripped_use = strip_internal_uses(line)
            if stripped_use is None:
                out_lines.append(f"// [amalgamated: dropped internal use] {line}" if line.endswith("\n") else f"// [amalgamated: dropped internal use] {line}\n")
                i += 1
                continue
            line = stripped_use
            m = DEF_RE.match(line)
            if m and not in_block_skip:
                kind = m.group(2)
                name = m.group(3)
                key = f"{kind}:{name}"
                if key in seen:
                    # Skip this entire top-level block: find its extent.
                    # Structs/enums/types: from here to matching closing at col 0?
                    # Fns/consts: single block — track brace depth + indentation.
                    skipped.append(f"{name} ({kind}) from {rel} (first in {seen[key]})")
                    out_lines.append(f"// [amalgamated: deduped {kind} {name} — canonical in {seen[key]}]\n")
                    # Determine skip extent: consume until blank-line + next top-level or balanced braces.
                    # Simple heuristic: if line contains ':' (struct/enum block) or '->' + ':' (fn block),
                    # skip until we dedent to col 0 non-indented line that isn't continuation.
                    j = i + 1
                    sig_done = line.rstrip().endswith(':')
                    while not sig_done and j < len(lines):
                        sj = lines[j].rstrip()
                        j += 1
                        if sj.endswith(':'):
                            sig_done = True
                    opens_block = sig_done
                    if opens_block:
                        # Skip indented block
                        while j < len(lines):
                            nxt = lines[j]
                            if nxt.strip() == "":
                                # Peek ahead: if next non-blank is indented or empty, keep skipping
                                k = j + 1
                                while k < len(lines) and lines[k].strip() == "":
                                    k += 1
                                if k < len(lines) and (lines[k].startswith(" ") or lines[k].startswith("\t")):
                                    j += 1
                                    continue
                                else:
                                    j += 1
                                    break
                            if nxt.startswith(" ") or nxt.startswith("\t"):
                                j += 1
                                continue
                            else:
                                break
                        i = j
                    else:
                        # Single-line const/type alias — skip one line
                        i += 1
                    continue
                else:
                    seen[key] = rel
                    out_lines.append(line)
                    i += 1
                    continue
            else:
                out_lines.append(line)
                i += 1
        out_lines.append(f"\n// === END: {rel} ===\n")

    out_path.write_text("".join(out_lines), encoding="utf-8")
    print(f"Wrote {out_path} ({len(out_lines)} lines)")
    print(f"Unique top-level symbols: {len(seen)}")
    print(f"Deduped {len(skipped)} mirrors:")
    for s in skipped:
        print(f"  - {s}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
